analyzer:
  strong-mode:
    implicit-casts: false
  exclude: [build/**]
  errors:
    uri_has_not_been_generated: ignore
  # Angular plugin support is in beta. You're welcome to try it and report
  # issues: https://github.com/dart-lang/angular_analyzer_plugin/issues
  # plugins:
    # - angular

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - avoid_empty_else
    - close_sinks
    - unnecessary_const
    - unnecessary_new